### PR TITLE
Use thrift python instead of shelling out to jar

### PR DESCRIPTION
**Pull request by robotblake**
This speeds up test runs immensely. I also verified that the queries produced for all of our datasets match 100%.

Note: The parquet_format files are generated using `thrift -r --gen python:dynamic parquet.thrift` against the parquet.thrift from https://github.com/apache/parquet-format.

---

This change is [Reviewable](https://reviewable.io/reviews/mozilla/parquet2hive/18)

### CODE REVIEW

**Comment by fbertsch** [comment]
Great patch. I do think we need at least a test for read_schema. I would split this into two commits where the first makes the function (done the old way with the jar) and makes a test for it, and the second implements the change that still passes the test. If that's too much for you, just add a test.

**Comment by robotblake** [comment]
@fbertsch Done.

**Comment by fbertsch** [comment]
@robotblake: LGTM. Please increase the version number.

**Comment by fbertsch** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/parquet2hive/18)_

**Pull request merged**
