### PR TITLE
Bug 1252826: Support _SUCCESS

### PR DESCRIPTION
**Pull request by fbertsch**
This change is [Reviewable](https://reviewable.io/reviews/mozilla/parquet2hive/5)

### CODE REVIEW

**Comment by vitillo** [comment]
Please add a meaningful commit message.

**Comment by vitillo** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[parquet2hive/parquet2hive, line 73 [r1]](https://reviewable.io:443/reviews/mozilla/parquet2hive/5#-KOoIZrdJ1xrHFcA7hGu:-KOoIZrdJ1xrHFcA7hGv:bu5ipq2) ([raw file](https://github.com/mozilla/parquet2hive/blob/4e5f7b8c037d0771a39a1ecc9f24b9354b03dac9/parquet2hive/parquet2hive#L73)):_

> ```
>             continue
> 
>         if success_only and not check_for_success(s3, bucket.name, version_prefix):
> ```

I don't think this is going to work if the dataset is partitioned, in which case the _SUCCESS files are stored within the partitions.

You should test these changes by writing a simple dummy dataset with Spark on S3 (use the telemetry-test-bucket bucket for testing).

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/parquet2hive/5)_

**Comment by fbertsch** [comment]
Changes made and commit message updated.

**Comment by vitillo** [comment]
Has this been tested both on a partitioned and non-partitioned dataset?

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[parquet2hive/parquet2hive, line 35 [r2]](https://reviewable.io:443/reviews/mozilla/parquet2hive/5#-KOxYzIinhGT087m2EKn:-KOxYzIinhGT087m2EKo:b-i7euw2) ([raw file](https://github.com/mozilla/parquet2hive/blob/6be9a3afc3d06dead32bc17226a4fd347add99f5/parquet2hive/parquet2hive#L35)):_

> ```
>     return re.findall("([^=/]+)=[^=/]+", prefix)
> 
> success_cache = {}
> ```

Please use the `lru_cache` decorator from functools32.

---

_[parquet2hive/parquet2hive, line 77 [r2]](https://reviewable.io:443/reviews/mozilla/parquet2hive/5#-KOxYH8OX3BfduzzSY0h:-KOxYH8PzEVHVEiBsgnf:b-2wafsh) ([raw file](https://github.com/mozilla/parquet2hive/blob/6be9a3afc3d06dead32bc17226a4fd347add99f5/parquet2hive/parquet2hive#L77)):_

> ```
>         version = tmp[-1]
>         if not re.match("^v[0-9]+$", version):
>             sys.stderr.write("Ignoring incompatible versioning scheme: version must be an integer prefixed with a 'v', found {}\n".format(version))
> ```

To be pedantic this change belongs in its commit.

---

_[parquet2hive/parquet2hive, line 94 [r2]](https://reviewable.io:443/reviews/mozilla/parquet2hive/5#-KOxXzSkQbTxLcERHGZe:-KOxXzSkQbTxLcERHGZf:b-v2ut57) ([raw file](https://github.com/mozilla/parquet2hive/blob/6be9a3afc3d06dead32bc17226a4fd347add99f5/parquet2hive/parquet2hive#L94)):_

> ```
>     versions = get_versions(bucket, prefix)
> 
>     if not versions:
> ```

To be pedantic this change belongs in its own commit.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/parquet2hive/5#-:-KOxXcVySwMuGrwpFu-W:b-7u4dpr)_

**Comment by fbertsch** [comment]
The changes requested have been made. I've removed the lines that should belong in their own commit, and later on may update some of the error and output messages.

This has been tested on:
non-partitioned, success missing: s3://telemetry-parquet/longitudinal
partitioned, success missing: s3://telemetry-test-bucket/churn/v1
non-partitioned, with success: s3://telemetry-parquet/client_count
partitioned, with success: s3://telemetry-test-bucket/churn/v2

**Comment by vitillo** [comment]
Looks good, please increase the version number so that we can upload this package to pypi.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/parquet2hive/5#-:-KOzRDBtvIuuSBwZNB6t:b-gd7zfp)_

**Comment by vitillo** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/parquet2hive/5)_

**Comment by fbertsch** [comment]
Version number has been increased.

**Pull request merged**
