### PR TITLE
Bug 1293665: Add tests to parquet2hive

### PR DESCRIPTION
**Pull request by fbertsch**
This pull request has been split into two commits. The first implements tests, and as few changes as possible to make the tests available to run and pass (minor code fixes). The second rearranges and changes the larger library file. The tests pass in both cases, separated so that it is obvious the changes pass the same tests as the original code.

I recommend diffing the first commits parquet2hivelib.py with the original parquet2hive file.

@vitillo r?

---

This change is [Reviewable](https://reviewable.io/reviews/mozilla/parquet2hive/10)

### CODE REVIEW

**Comment by vitillo** [comment]
Please [break up the PR](https://github.com/mozilla/telemetry-onboarding/blob/master/Contributing.md) in a set of atomic commits. Each commit should have a descriptive title and a comment that clearly states why the change was needed.  `Cosmetic changes and cleanup for the parquet2hive library` is not a great title. Furthermore it doesn't have a description.

I think it makes sense to first re-arrange the project structure, with one or more commits, and then add the tests, with one or more commits.

**Comment by fbertsch** [comment]
Commits have been broken up.

@vitillo r?

**Comment by vitillo** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

_[tests/parquet2hive_test.py, line 8 [r1]](https://reviewable.io:443/reviews/mozilla/parquet2hive/10#-KQuI4U3ojiaC2lKW3xq:-KQuI4U3ojiaC2lKW3xr:b-w8390x) ([raw file](https://github.com/mozilla/parquet2hive/blob/0dec89a39dda5c4f9625095016fd4efd4a12aa53/tests/parquet2hive_test.py#L8)):_

> ``` Python
> This setup_str is used instead of actually calling the code 
>     because the bucket did not persist across different functions
>     that used @mock_s3.
> ```

This isn't very elegant. I am sure you had a good reason to do it but it's not clear to me what it is just by reading the comment. Can't you just call a function instead of executing a string?

---

_[tests/parquet2hive_test.py, line 19 [r1]](https://reviewable.io:443/reviews/mozilla/parquet2hive/10#-KQuJ3kuu_Z_NgzgFrIN:-KQuJ3kuu_Z_NgzgFrIO:bsygo09) ([raw file](https://github.com/mozilla/parquet2hive/blob/0dec89a39dda5c4f9625095016fd4efd4a12aa53/tests/parquet2hive_test.py#L19)):_

> ``` Python
> bucket = s3.Bucket(bucket_name)
> dataset_file = 'tests/dataset.parquet'
> simple_dataset_file = 'tests/simple-dataset.parquet'"""
> ```

Is `simple_dataset_file` used at all?

---

_[tests/parquet2hive_test.py, line 51 [r1]](https://reviewable.io:443/reviews/mozilla/parquet2hive/10#-KQuJvX9M_cJ1recQD2_:-KQuJvXAOZL6s1oNXxA4:b4yycaw) ([raw file](https://github.com/mozilla/parquet2hive/blob/0dec89a39dda5c4f9625095016fd4efd4a12aa53/tests/parquet2hive_test.py#L51)):_

> ``` Python
> 
>         assert 'v3' not in bash_cmd, 'Should only process v2, but found v3'
>         assert 'v2' in bash_cmd, 'Should process v2, but didnt'
> ```

s\didnt'\didn't

---

_[tests/parquet2hive_test.py, line 81 [r1]](https://reviewable.io:443/reviews/mozilla/parquet2hive/10#-KQuKGe8cYxvSwST7_mf:-KQuKGe8cYxvSwST7_mg:b-oi8zz4) ([raw file](https://github.com/mozilla/parquet2hive/blob/0dec89a39dda5c4f9625095016fd4efd4a12aa53/tests/parquet2hive_test.py#L81)):_

> ``` Python
> 
>         assert 'v3' in bash_cmd, 'Should process v3 but didnt'
>         assert 'v2' not in bash_cmd, 'Should not process v2 since success is missing, but did'
> ```

s\success\SUCCESS file

---

_[tests/parquet2hive_test.py, line 197 [r1]](https://reviewable.io:443/reviews/mozilla/parquet2hive/10#-KQuKhd2CoBRqg6s9cCy:-KQuKhd3cApYATsO3Se7:b-oi8zz4) ([raw file](https://github.com/mozilla/parquet2hive/blob/0dec89a39dda5c4f9625095016fd4efd4a12aa53/tests/parquet2hive_test.py#L197)):_

> ``` Python
>             s3_client.put_object(Bucket = bucket_name, Key = k, Body = b'teststring')
> 
>         assert lib.check_success_exists(s3, bucket_name, '/'.join([prefix, version, partition])), 'success not found in partition when it exists'
> ```

s\success\SUCCESS file

---

_[tests/parquet2hive_test.py, line 209 [r1]](https://reviewable.io:443/reviews/mozilla/parquet2hive/10#-KQuKkvgwx_Jp0GGjy7I:-KQuKkvgwx_Jp0GGjy7J:b-oi8zz4) ([raw file](https://github.com/mozilla/parquet2hive/blob/0dec89a39dda5c4f9625095016fd4efd4a12aa53/tests/parquet2hive_test.py#L209)):_

> ``` Python
>             s3_client.put_object(Bucket = bucket_name, Key = k, Body = b'teststring')
> 
>         assert lib.check_success_exists(s3, bucket_name, '/'.join([prefix, version])), 'success not found in dir when it exists'
> ```

s\success\SUCCESS file

---

_[tests/parquet2hive_test.py, line 222 [r1]](https://reviewable.io:443/reviews/mozilla/parquet2hive/10#-KQuKp9ENURZrD2J4gPS:-KQuKp9ENURZrD2J4gPT:b-oi8zz4) ([raw file](https://github.com/mozilla/parquet2hive/blob/0dec89a39dda5c4f9625095016fd4efd4a12aa53/tests/parquet2hive_test.py#L222)):_

> ``` Python
>             s3_client.put_object(Bucket = bucket_name, Key = k, Body = b'teststring')
> 
>         assert not lib.check_success_exists(s3, bucket_name, '/'.join([prefix, version, partition])), 'success found when actually missing from partition'
> ```

s\success\SUCCESS file

---

_[tests/parquet2hive_test.py, line 234 [r1]](https://reviewable.io:443/reviews/mozilla/parquet2hive/10#-KQuKpsuF9atsaChEkN2:-KQuKpsuF9atsaChEkN3:b-oi8zz4) ([raw file](https://github.com/mozilla/parquet2hive/blob/0dec89a39dda5c4f9625095016fd4efd4a12aa53/tests/parquet2hive_test.py#L234)):_

> ``` Python
>             s3_client.put_object(Bucket = bucket_name, Key = k, Body = b'teststring')
> 
>         assert not lib.check_success_exists(s3, bucket_name, '/'.join([prefix, version])), 'success found when actually missing from directory'
> ```

s\success\SUCCESS file

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/parquet2hive/10)_

**Comment by fbertsch** [comment]
Review status: 2 of 7 files reviewed at latest revision, 8 unresolved discussions.

---

_[tests/parquet2hive_test.py, line 8 [r1]](https://reviewable.io:443/reviews/mozilla/parquet2hive/10#-KQuI4U3ojiaC2lKW3xq:-KR-2NDZggywkfIrqvrB:bpoahux) ([raw file](https://github.com/mozilla/parquet2hive/blob/0dec89a39dda5c4f9625095016fd4efd4a12aa53/tests/parquet2hive_test.py#L8)):_
<details><summary>

<i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>



> This isn't very elegant. I am sure you had a good reason to do it but it's not clear to me what it is just by reading the comment. Can't you just call a function instead of executing a string?
> </details>
> Done. For some reason this wasn't working before - now it seems to be okay.

---

_[tests/parquet2hive_test.py, line 19 [r1]](https://reviewable.io:443/reviews/mozilla/parquet2hive/10#-KQuJ3kuu_Z_NgzgFrIN:-KR-2VEumSUSFdqTdb-Q:bss4a2b) ([raw file](https://github.com/mozilla/parquet2hive/blob/0dec89a39dda5c4f9625095016fd4efd4a12aa53/tests/parquet2hive_test.py#L19)):_
<details><summary>

<i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>



> Is `simple_dataset_file` used at all?
> </details>
> Removed.

---

_[tests/parquet2hive_test.py, line 51 [r1]](https://reviewable.io:443/reviews/mozilla/parquet2hive/10#-KQuJvX9M_cJ1recQD2_:-KR-2XrpD9JP0gblcdPf:b-896fix) ([raw file](https://github.com/mozilla/parquet2hive/blob/0dec89a39dda5c4f9625095016fd4efd4a12aa53/tests/parquet2hive_test.py#L51)):_
<details><summary>

<i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>



> s\didnt'\didn't
> </details>
> Done.

---

_[tests/parquet2hive_test.py, line 81 [r1]](https://reviewable.io:443/reviews/mozilla/parquet2hive/10#-KQuKGe8cYxvSwST7_mf:-KR-2YS03WzL4xgidXW3:b-896fix) ([raw file](https://github.com/mozilla/parquet2hive/blob/0dec89a39dda5c4f9625095016fd4efd4a12aa53/tests/parquet2hive_test.py#L81)):_
<details><summary>

<i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>



> s\success\SUCCESS file
> </details>
> Done.

---

_[tests/parquet2hive_test.py, line 197 [r1]](https://reviewable.io:443/reviews/mozilla/parquet2hive/10#-KQuKhd2CoBRqg6s9cCy:-KR-2ZPA_O5xxbPdgT9T:b-896fix) ([raw file](https://github.com/mozilla/parquet2hive/blob/0dec89a39dda5c4f9625095016fd4efd4a12aa53/tests/parquet2hive_test.py#L197)):_
<details><summary>

<i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>



> s\success\SUCCESS file
> </details>
> Done.

---

_[tests/parquet2hive_test.py, line 209 [r1]](https://reviewable.io:443/reviews/mozilla/parquet2hive/10#-KQuKkvgwx_Jp0GGjy7I:-KR-2ZodOrSVB9L_30Ec:b-896fix) ([raw file](https://github.com/mozilla/parquet2hive/blob/0dec89a39dda5c4f9625095016fd4efd4a12aa53/tests/parquet2hive_test.py#L209)):_
<details><summary>

<i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>



> s\success\SUCCESS file
> </details>
> Done.

---

_[tests/parquet2hive_test.py, line 222 [r1]](https://reviewable.io:443/reviews/mozilla/parquet2hive/10#-KQuKp9ENURZrD2J4gPS:-KR-2_LTZu4wUj266QXp:b-896fix) ([raw file](https://github.com/mozilla/parquet2hive/blob/0dec89a39dda5c4f9625095016fd4efd4a12aa53/tests/parquet2hive_test.py#L222)):_
<details><summary>

<i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>



> s\success\SUCCESS file
> </details>
> Done.

---

_[tests/parquet2hive_test.py, line 234 [r1]](https://reviewable.io:443/reviews/mozilla/parquet2hive/10#-KQuKpsuF9atsaChEkN2:-KR-2tGVIxrknXR8Qn2y:b-896fix) ([raw file](https://github.com/mozilla/parquet2hive/blob/0dec89a39dda5c4f9625095016fd4efd4a12aa53/tests/parquet2hive_test.py#L234)):_
<details><summary>

<i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>



> s\success\SUCCESS file
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/parquet2hive/10)_

**Comment by fbertsch** [comment]
Fixed up the spelling and the function. Ready for another review @vitillo

**Comment by vitillo** [comment]
Please increase the version number.

---

Reviewed 4 of 5 files at r3, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/parquet2hive/10#-:-KR-BGgmF_7WOUlVQ_r2:b-d4b8nz)_

**Comment by fbertsch** [comment]
@vitillo bumped version number, ready for merge

**Comment by vitillo** [comment]
Looks good, thanks!

**Comment by vitillo** [comment]
Please ship the package to pypi.

**Pull request merged**
