### PR TITLE
Bugs 1305473, 1305429 - New CLI options

### PR DESCRIPTION
**Pull request by fbertsch**
Added alias and regex exclusion options. @vitillo r?

---

This change is [Reviewable](https://reviewable.io/reviews/mozilla/parquet2hive/24)

### CODE REVIEW

**Comment by vitillo** [comment]
Reviewed 3 of 3 files at r1, 3 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[parquet2hive, line 28 at r2](https://reviewable.io:443/reviews/mozilla/parquet2hive/24#-KTnvLFEktndZJ2ArHI3:-KTnvLFFFwQEsSsMnsCa:bekybp2) ([raw file](https://github.com/mozilla/parquet2hive/blob/d06ffe2e48c80cd83a9099b3d1fc2d97bb248087/parquet2hive#L28)):_

> ```
> 
>     parser.add_argument('--exclude-regex', type=str, default=None, nargs='*',
>                         help='Use an alternate name for this dataset')
> ```

`help` argument is incorrect

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/parquet2hive/24)_

**Comment by fbertsch** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

_[parquet2hive, line 28 at r2](https://reviewable.io:443/reviews/mozilla/parquet2hive/24#-KTnvLFEktndZJ2ArHI3:-KToVNwNgpvVI7mhszKo:b-896fix) ([raw file](https://github.com/mozilla/parquet2hive/blob/d06ffe2e48c80cd83a9099b3d1fc2d97bb248087/parquet2hive#L28)):_
<details><summary>

<i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>



> `help` argument is incorrect
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/parquet2hive/24)_

**Comment by fbertsch** [comment]
@vitillo RFAL

**Comment by vitillo** [comment]
Reviewed 2 of 2 files at r4.
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

_[parquet2hive, line 28 at r4](https://reviewable.io:443/reviews/mozilla/parquet2hive/24#-KTtWvFs5QlYZjr6psoZ:-KTtWvFt4GrGH8mkxqDD:b-b0snff) ([raw file](https://github.com/mozilla/parquet2hive/blob/178e5a93e2e4c3053b8c712ee5b37a746dba46c1/parquet2hive#L28)):_

> ```
> 
>     parser.add_argument('--exclude-regex', type=str, default=None, nargs='*',
>                         help='A regex pattern which causes any object that match it to be ignored')
> ```

s/object/objects

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/parquet2hive/24)_

**Comment by fbertsch** [comment]
Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

_[parquet2hive, line 28 at r4](https://reviewable.io:443/reviews/mozilla/parquet2hive/24#-KTtWvFs5QlYZjr6psoZ:-KTtXpGsAeC6NHlpu8mQ:b-896fix) ([raw file](https://github.com/mozilla/parquet2hive/blob/178e5a93e2e4c3053b8c712ee5b37a746dba46c1/parquet2hive#L28)):_
<details><summary>

<i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>



> s/object/objects
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/parquet2hive/24)_

**Comment by vitillo** [comment]
Reviewed 1 of 1 files at r5.
Review status: 3 of 5 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/parquet2hive/24)_

**Comment by vitillo** [comment]
r+

**Pull request merged**
