### PR TITLE
Bug 1301386 - p2h loads all datasets within a prefix

### PR DESCRIPTION
**Pull request by fbertsch**
This change is [Reviewable](https://reviewable.io/reviews/mozilla/parquet2hive/25)

### CODE REVIEW

**Comment by fbertsch** [comment]
Our ultimate goal will be to include speed improvements to p2h, so that this can be run more often on a prefix with an ever-changing set of datasets, and ingestion latency wouldn't be affected (too much, at least).

@vitillo, r?

**Comment by vitillo** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[parquet2hive_modules/parquet2hivelib.py, line 47 at r1](https://reviewable.io:443/reviews/mozilla/parquet2hive/25#-KZWBNfE-Wykpx2KTd8t:-KZWBNfE-Wykpx2KTd8u:b-7y2qp6) ([raw file](https://github.com/mozilla/parquet2hive/blob/14f0ed58df87fd6e32c8945a2d62936ff2cf1b6c/parquet2hive_modules/parquet2hivelib.py#L47)):*
> ```Python
> 
> def get_bash_cmd(dataset, success_only=False, recent_versions=None, version=None, alias=None, exclude_regex=None):
>     dataset = _remove_trailing_backslash(dataset)    
> ```

Please remove extra whitespace.

---

*[parquet2hive_modules/parquet2hivelib.py, line 48 at r1](https://reviewable.io:443/reviews/mozilla/parquet2hive/25#-KZWB1mUMFO5iE2hGKRG:-KZWB1mUMFO5iE2hGKRH:b-540zjh) ([raw file](https://github.com/mozilla/parquet2hive/blob/14f0ed58df87fd6e32c8945a2d62936ff2cf1b6c/parquet2hive_modules/parquet2hivelib.py#L48)):*
> ```Python
> def get_bash_cmd(dataset, success_only=False, recent_versions=None, version=None, alias=None, exclude_regex=None):
>     dataset = _remove_trailing_backslash(dataset)    
>     bucket_name, prefix = _get_bucket_and_prefix(dataset)
> ```

It would be convenient to deal with the trailing backslash within `_get_bucket_and_prefix`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/parquet2hive/25#-:-KZWC2vcg50-RM42IySN:bnfp4nl)*

**Comment by fbertsch** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[parquet2hive_modules/parquet2hivelib.py, line 47 at r1](https://reviewable.io:443/reviews/mozilla/parquet2hive/25#-KZWBNfE-Wykpx2KTd8t:-KZaqBUkbja9Nj8idj1M:b-896fix) ([raw file](https://github.com/mozilla/parquet2hive/blob/14f0ed58df87fd6e32c8945a2d62936ff2cf1b6c/parquet2hive_modules/parquet2hivelib.py#L47)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary><blockquote>

Please remove extra whitespace.
</blockquote></details>

Done.

---

*[parquet2hive_modules/parquet2hivelib.py, line 48 at r1](https://reviewable.io:443/reviews/mozilla/parquet2hive/25#-KZWB1mUMFO5iE2hGKRG:-KZaqC0DEenCWBKv-TEF:b-896fix) ([raw file](https://github.com/mozilla/parquet2hive/blob/14f0ed58df87fd6e32c8945a2d62936ff2cf1b6c/parquet2hive_modules/parquet2hivelib.py#L48)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary><blockquote>

It would be convenient to deal with the trailing backslash within `_get_bucket_and_prefix`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/parquet2hive/25)*

**Comment by fbertsch** [comment]
Hrm. The build broke. All the tests are passing locally. I'll have to pick this up next week

**Comment by fbertsch** [comment]
@vitillo, fixed the build (regression was caused from a new version of functools). Otherwise, just made the minor changes you had mentioned.

**Comment by vitillo** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/parquet2hive/25#-:-K_8ZL_bi6Z3MDknv_n7:bnfp4nl)*

**Pull request merged**
