### PR TITLE
Bug 1301047: Add travis support

### PR DESCRIPTION
**Pull request by fbertsch**
This change is [Reviewable](https://reviewable.io/reviews/mozilla/parquet2hive/20)

### CODE REVIEW

**Comment by fbertsch** [comment]
@vitillo r?

**Comment by fbertsch** [comment]
Well hold off on that. Suddenly it fails again... ugh. I'll deal with it on Monday.

**Comment by fbertsch** [comment]
@vitillo now it's ready for review :)

**Comment by vitillo** [comment]
Looks good, thanks!

**Pull request merged**
