### PR TITLE
Bug 1286248, Bug 1255741, Bug 1255739 - Changes related to versions

### PR DESCRIPTION
**Pull request by fbertsch**
These are all similar changes that affect which versions are processed.

---

This change is [Reviewable](https://reviewable.io/reviews/vitillo/parquet2hive/4)

### CODE REVIEW

**Comment by vitillo** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[parquet2hive/parquet2hive, line 56 [r1]](https://reviewable.io:443/reviews/vitillo/parquet2hive/4#-KOjXiCzf469sW_fy0gb:-KOjXiCzf469sW_fy0gc:b-k37uf1) ([raw file](https://github.com/vitillo/parquet2hive/blob/fef22b6cc3167542a7f3af5437ae1593dee3a241/parquet2hive/parquet2hive#L56)):_

> ```
> 
>     return [(prefix, name, "v{}".format(version)) 
>       for (prefix, name, version) 
> ```

It seems that you are using tabs for indentation. Please use spaces; the same applies for the rest of the patch.

---

_[parquet2hive/parquet2hive, line 57 [r1]](https://reviewable.io:443/reviews/vitillo/parquet2hive/4#-KOjYXcAc9WdALTD5ha0:-KOjYXcBZvC5ZBWj-emr:b-xfzphy) ([raw file](https://github.com/vitillo/parquet2hive/blob/fef22b6cc3167542a7f3af5437ae1593dee3a241/parquet2hive/parquet2hive#L57)):_

> ```
>     return [(prefix, name, "v{}".format(version)) 
>       for (prefix, name, version) 
>       in sorted(result, key = lambda x : -x[2])]
> ```

Please use the `reverse` parameter.

---

_[parquet2hive/parquet2hive, line 180 [r1]](https://reviewable.io:443/reviews/vitillo/parquet2hive/4#-KOj_Z4zaEOAKDwqDkIy:-KOj_Z5-qjqfr5ztpq2H:b-v4hqcl) ([raw file](https://github.com/vitillo/parquet2hive/blob/fef22b6cc3167542a7f3af5437ae1593dee3a241/parquet2hive/parquet2hive#L180)):_

> ```
>           help="S3 path to Parquet dataset with the following layout s3://BUCKET/DATASET/vVERSION/DIM=VALUE/.../DIM=VALUE/FILE")
> 
>     parser.add_argument('--dversion', '-dv', default=None,
> ```

Please use `dataset-version`.

---

_[parquet2hive/parquet2hive, line 183 [r1]](https://reviewable.io:443/reviews/vitillo/parquet2hive/4#-KOj_e-tXc96M_KDD2Wp:-KOj_e-tXc96M_KDD2Wq:b6f93vn) ([raw file](https://github.com/vitillo/parquet2hive/blob/fef22b6cc3167542a7f3af5437ae1593dee3a241/parquet2hive/parquet2hive#L183)):_

> ```
>           help="Specify version of the dataset to use with format vyyyymmdd, e.g. v20160514. Cannot be used with rversion" )
> 
>     parser.add_argument('--rversion', '-rv', action='store_true',
> ```

Please use `use-last-version`

---

_[parquet2hive/parquet2hive, line 184 [r1]](https://reviewable.io:443/reviews/vitillo/parquet2hive/4#-KOja5KBxV-fmtzvnEVl:-KOja5KCF-7tbm0tXWFg:b-9g7s23) ([raw file](https://github.com/vitillo/parquet2hive/blob/fef22b6cc3167542a7f3af5437ae1593dee3a241/parquet2hive/parquet2hive#L184)):_

> ```
> 
>     parser.add_argument('--rversion', '-rv', action='store_true',
>           help='Store only the most recent version of the dataset, cannot be used with dversion')
> ```

s/Store/Load

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vitillo/parquet2hive/4)_

**Comment by vitillo** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/parquet2hive/4)_

**Comment by vitillo** [comment]
Please update the version number in `setup.py`.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/parquet2hive/4#-:-KOoEzkpV5XCDXEU_dKO:bdpoxnr)_

**Comment by vitillo** [comment]
Please rebase the latest commit (see our [guidelines](https://github.com/mozilla/telemetry-onboarding/blob/master/Contributing.md)). 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/parquet2hive/4#-:-KOoFFe_UyJy5mp9zUCb:b3o7vch)_

**Comment by fbertsch** [comment]
Version number has been updated and commits squashed into 2541f16.

**Comment by vitillo** [comment]
Now all the changes done after the first push are merged in the last commit. This is not what I intended. Let me try to be more clear: say you have three commits A, B & C; then the reviewer asks you to change something that logically belongs to commit A. What you should do is to use `git rebase -i`, as shown [here](https://github.com/mozilla/telemetry-onboarding/blob/master/Contributing.md), to edit commit A. In other words, changes to commit A should land in commit A, not in B or C.

**Comment by fbertsch** [comment]
I've put all the changes with their appropriate commits, so everything is atomic now.

**Comment by vitillo** [comment]
This PR conflicts now with the `master` branch and can't be automatically merged, please rebase it.

**Comment by fbertsch** [comment]
Changes have been rebased on top of master.

**Comment by vitillo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[parquet2hive/parquet2hive, line 99 [r6]](https://reviewable.io:443/reviews/mozilla/parquet2hive/4#-KPHvJoxdCH2d1Iy0kMv:-KPHvJoyBEgmZX1h_gna:bbgnuap) ([raw file](https://github.com/mozilla/parquet2hive/blob/b89761cdf04682bcd8060faa1d9191bc71ba5fa9/parquet2hive/parquet2hive#L99)):_

> ```
> 
>     if recent_version:
>         versions = [ max(versions, key = lambda x : int(x[2][1:])) ]
> ```

This is not going to work well with `success_only`. E.g. say there are two versions for a dataset: v1 & v2 but the latter is currently being generated. Then, parquet2hive should load the most recent version that contains a _SUCCESS file, which is v1. In other words, if `success_only` is set parquet2hive should work as if incomplete datasets don't exist. 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/parquet2hive/4)_

**Comment by vitillo** [comment]
Reviewed 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/parquet2hive/4)_

**Comment by fbertsch** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[parquet2hive/parquet2hive, line 99 [r6]](https://reviewable.io:443/reviews/mozilla/parquet2hive/4#-KPHvJoxdCH2d1Iy0kMv:-KPIwHUk_EORAjZZQTi0:b-64zlek) ([raw file](https://github.com/mozilla/parquet2hive/blob/b89761cdf04682bcd8060faa1d9191bc71ba5fa9/parquet2hive/parquet2hive#L99)):_
<details><summary>

<i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>



> This is not going to work well with `success_only`. E.g. say there are two versions for a dataset: v1 & v2 but the latter is currently being generated. Then, parquet2hive should load the most recent version that contains a _SUCCESS file, which is v1. In other words, if `success_only` is set parquet2hive should work as if incomplete datasets don't exist. 
> </details>
> Thanks for the clarification. This update should do the trick, and it was tested against that case in s3://telemetry-test-bucket/churn, where v3 did not have a success file, but v2 did.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/parquet2hive/4)_

**Comment by vitillo** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/parquet2hive/4#-:-KPNchLA3UhY6VLWj_T_:bnfp4nl)_

**Comment by vitillo** [comment]
Please upload the latest version to pypi.

**Pull request merged**
