### PR TITLE
 Bug 1304421 - Parquet2hive fails on non-parquet files

### PR DESCRIPTION
**Pull request by fbertsch**
Also cleaned up the code a bit. Easy to do with the tests.

@vitillo: r?

---

This change is [Reviewable](https://reviewable.io/reviews/mozilla/parquet2hive/16)

### CODE REVIEW

**Comment by vitillo** [comment]
Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[parquet2hive_modules/parquet2hivelib.py, line 45 at r1](https://reviewable.io:443/reviews/mozilla/parquet2hive/16#-KSa_z0_8YU4GnAqj4rT:-KSa_z0aMbyLEifEAPTJ:b-elnt6z) ([raw file](https://github.com/mozilla/parquet2hive/blob/237222dd23bf0c7f0da2c0159c2464db8892c5ea/parquet2hive_modules/parquet2hivelib.py#L45)):_

> ``` Python
>             break
> 
>         if not sample:
> ```

Please use a meaningful commit title and description.

---

_[parquet2hive_modules/parquet2hivelib.py, line 120 at r1](https://reviewable.io:443/reviews/mozilla/parquet2hive/16#-KSaZpAxTSOR8gOhlsTg:-KSaZpAxTSOR8gOhlsTh:b-vgv6mi) ([raw file](https://github.com/mozilla/parquet2hive/blob/237222dd23bf0c7f0da2c0159c2464db8892c5ea/parquet2hive_modules/parquet2hivelib.py#L120)):_

> ``` Python
> def ignore_key(key):
>     is_folder = key.endswith('/')
>     temp_file_or_dir = any([f.startswith('_') for f in key.split('/')])
> ```

What about generalizing this method using a list of regular expressions? That would make it easier to add new patterns in the future (or even add a configuration option to pass new patterns).

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/parquet2hive/16)_

**Comment by fbertsch** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[parquet2hive_modules/parquet2hivelib.py, line 120 at r1](https://reviewable.io:443/reviews/mozilla/parquet2hive/16#-KSaZpAxTSOR8gOhlsTg:-KSanf0L7rLTXAODoxwU:b-xp5zia) ([raw file](https://github.com/mozilla/parquet2hive/blob/237222dd23bf0c7f0da2c0159c2464db8892c5ea/parquet2hive_modules/parquet2hivelib.py#L120)):_
<details><summary>

<i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>



> What about generalizing this method using a list of regular expressions? That would make it easier to add new patterns in the future (or even add a configuration option to pass new patterns).
> </details>
> That is fine with me. I'll make it read a list right now, and add a bug for a new configuration option.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/parquet2hive/16)_

**Comment by fbertsch** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

_[parquet2hive_modules/parquet2hivelib.py, line 45 at r1](https://reviewable.io:443/reviews/mozilla/parquet2hive/16#-KSa_z0_8YU4GnAqj4rT:-KSatKWnPdEfPGwRPyDN:b-896fix) ([raw file](https://github.com/mozilla/parquet2hive/blob/237222dd23bf0c7f0da2c0159c2464db8892c5ea/parquet2hive_modules/parquet2hivelib.py#L45)):_
<details><summary>

<i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>



> Please use a meaningful commit title and description.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/parquet2hive/16)_

**Comment by fbertsch** [comment]
@vitillo r?

**Comment by vitillo** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/parquet2hive/16#-:-KSb2sTifA5LJOHJ5xxd:bnfp4nl)_

**Comment by vitillo** [comment]
Please bump the version number.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/parquet2hive/16#-:-KSb30F57o2q7s-TYbfW:b-szqg4r)_

**Comment by fbertsch** [comment]
@vitillo bumped

**Comment by vitillo** [comment]
@fbertsch Please deploy the new version on our Presto master; you might also want to run a quick manual test to check that it works as expected for the datasets imported with cron.

**Comment by fbertsch** [comment]
@vitillo Tested on our current datasets (including the failing mobile ones), Updated the pypi repository version, and pushed the new version to the presto master.

**Pull request merged**
