### PR TITLE
Allow fixed_len_byte_array in p2h

### PR DESCRIPTION
**Pull request by fbertsch**
This change is [Reviewable](https://reviewable.io/reviews/mozilla/parquet2hive/36)

### CODE REVIEW

**Comment by robotblake** [comment]
What's generating the `fixed_len_byte_array`? If it's also got a `converted_type` of `utf8` than shouldn't it be a `char(n)` with the length pulled out?

**Comment by fbertsch** [comment]
That comes directly from here: https://pipeline-cep.prod.mozaws.net/dashboard_output/analysis.moz_telemetry_parquet_schema.parquet.txt

Note the UUID field. I suppose we could cast it as the logical string type, but we'll still run into the problem again in the future.

**Comment by fbertsch** [comment]
Looks like the build failed because of https://github.com/travis-ci/travis-ci/issues/7940

**Comment by robotblake** [comment]
Actually having it not be a string is correct in this instance as 16 bytes means it is actually going to be binary. I'll merge this and then try and push a fix for the build failure.

**Review by robotblake — APPROVED** [review]
👍

**Pull request merged**
