### PR TITLE
Use partial / range gets instead of downloading entire file

### PR DESCRIPTION
**Pull request by robotblake**
This change is [Reviewable](https://reviewable.io/reviews/mozilla/parquet2hive/22)

### CODE REVIEW

**Comment by vitillo** [comment]
@fbertsch r?

**Comment by vitillo** [comment]
@robotblake , our usual process is to open a Bug on Bugzilla and ask someone to review the PR.

**Comment by fbertsch** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[parquet2hive_modules/parquet2hivelib.py, line 89 at r1](https://reviewable.io:443/reviews/mozilla/parquet2hive/22#-KTVNz6hFyyLzZ2-FOen:-KTVNz6hFyyLzZ2-FOeo:b-s65djt) ([raw file](https://github.com/mozilla/parquet2hive/blob/050ee2e84b884804761df42e8b5531abda3e70d8/parquet2hive_modules/parquet2hivelib.py#L89)):_

> ``` Python
> 
>     # get footer size
>     response = s3obj.get(Range='bytes={}-'.format(object_size - 8))
> ```

I guess I should have asked this earlier, but how does failure look in this case? When we run into a file that is not parquet?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/parquet2hive/22)_

**Comment by robotblake** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[parquet2hive_modules/parquet2hivelib.py, line 89 at r1](https://reviewable.io:443/reviews/mozilla/parquet2hive/22#-KTVNz6hFyyLzZ2-FOen:-KTVQwo8F0oD_3AtXcLk:b1hja5g) ([raw file](https://github.com/mozilla/parquet2hive/blob/050ee2e84b884804761df42e8b5531abda3e70d8/parquet2hive_modules/parquet2hivelib.py#L89)):_
<details><summary>

<i>Previously, fbertsch (Frank Bertsch) wrote…</i></summary>



> I guess I should have asked this earlier, but how does failure look in this case? When we run into a file that is not parquet?
> </details>
> Looks like there are several failure cases.
- When `object_size < 8` boto3 raises `ValueError: too many values to unpack`
- When `object_size < 8 + footer_size` boto3 raises `ValueError: too many values to unpack`
- When there are enough bytes to read the footer but it's not valid thrift raises a `KeyError`

The solution for this (I think?) would be to check that the last four bytes match `PAR1` as per the parquet spec (and maybe check that the `Range` param is valid based on the `object_size`) and raise an exception accordingly.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/parquet2hive/22)_

**Comment by fbertsch** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[parquet2hive_modules/parquet2hivelib.py, line 89 at r1](https://reviewable.io:443/reviews/mozilla/parquet2hive/22#-KTVNz6hFyyLzZ2-FOen:-KTVXs9VPad506RebrrS:b-6r3v7b) ([raw file](https://github.com/mozilla/parquet2hive/blob/050ee2e84b884804761df42e8b5531abda3e70d8/parquet2hive_modules/parquet2hivelib.py#L89)):_
<details><summary>

<i>Previously, robotblake (Blake Imsland) wrote…</i></summary>



> Looks like there are several failure cases.
> - When `object_size < 8` boto3 raises `ValueError: too many values to unpack`
> - When `object_size < 8 + footer_size` boto3 raises `ValueError: too many values to unpack`
> - When there are enough bytes to read the footer but it's not valid thrift raises a `KeyError`
> 
> The solution for this (I think?) would be to check that the last four bytes match `PAR1` as per the parquet spec (and maybe check that the `Range` param is valid based on the `object_size`) and raise an exception accordingly.
> </details>
> I like this solution. Checking against the magic number should solve the problem. Why don't you have it raise a specific exception, and include a test that shows this.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/parquet2hive/22)_

**Comment by robotblake** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[parquet2hive_modules/parquet2hivelib.py, line 89 at r1](https://reviewable.io:443/reviews/mozilla/parquet2hive/22#-KTVNz6hFyyLzZ2-FOen:-KTVb6r0x2Y1KA_YZYdB:b-896fix) ([raw file](https://github.com/mozilla/parquet2hive/blob/050ee2e84b884804761df42e8b5531abda3e70d8/parquet2hive_modules/parquet2hivelib.py#L89)):_
<details><summary>

<i>Previously, fbertsch (Frank Bertsch) wrote…</i></summary>



> I like this solution. Checking against the magic number should solve the problem. Why don't you have it raise a specific exception, and include a test that shows this.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/parquet2hive/22)_

**Comment by fbertsch** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[parquet2hive_modules/parquet2hivelib.py, line 89 at r1](https://reviewable.io:443/reviews/mozilla/parquet2hive/22#-KTVNz6hFyyLzZ2-FOen:-KTVbUQP1bzUL5KTTt-0:b-q8a5uy) ([raw file](https://github.com/mozilla/parquet2hive/blob/050ee2e84b884804761df42e8b5531abda3e70d8/parquet2hive_modules/parquet2hivelib.py#L89)):_
<details><summary>

<i>Previously, robotblake (Blake Imsland) wrote…</i></summary>



> Done.
> </details>
> Sorry, should have also said "yes" to checking the range param. Won't the first two exceptions you mentioned still get raised? I think we want them all to instead by ParquetFormatError.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/parquet2hive/22)_

**Comment by fbertsch** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[parquet2hive_modules/parquet2hivelib.py, line 89 at r1](https://reviewable.io:443/reviews/mozilla/parquet2hive/22#-KTVNz6hFyyLzZ2-FOen:-KTVbkh3HGo_0AldQMNo:b-sm0f3h) ([raw file](https://github.com/mozilla/parquet2hive/blob/050ee2e84b884804761df42e8b5531abda3e70d8/parquet2hive_modules/parquet2hivelib.py#L89)):_
<details><summary>

<i>Previously, fbertsch (Frank Bertsch) wrote…</i></summary>



> Sorry, should have also said "yes" to checking the range param. Won't the first two exceptions you mentioned still get raised? I think we want them all to instead by ParquetFormatError.
> </details>
> *all instead raise ParquetFormatError

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/parquet2hive/22)_

**Comment by robotblake** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[parquet2hive_modules/parquet2hivelib.py, line 89 at r1](https://reviewable.io:443/reviews/mozilla/parquet2hive/22#-KTVNz6hFyyLzZ2-FOen:-KTVeK0ZDawkLkRDntYl:b-896fix) ([raw file](https://github.com/mozilla/parquet2hive/blob/050ee2e84b884804761df42e8b5531abda3e70d8/parquet2hive_modules/parquet2hivelib.py#L89)):_
<details><summary>

<i>Previously, fbertsch (Frank Bertsch) wrote…</i></summary>



> *all instead raise ParquetFormatError
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/parquet2hive/22)_

**Comment by fbertsch** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/parquet2hive/22#-:-KTVelf9TGvQLsinE_pI:bnfp4nl)_

**Pull request merged**
